name = "zhconv"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-29"

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
# BODY_LIMIT = "2097152"

# Set it via `wrangler secret put API_TOKEN` instead.
## API_TOKEN = "e72ffa14-e7c8-4abd-a698-a675231a1a8e" 
