name: Deploy Worker
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: echo '${{ toJSON(github.event) }}' | jq .
      - name: Disable other workflows in Workers fork
        if: github.event_name == 'repository_dispatch' && github.event.repository.fork == true
        run: gh workflow list --json 'name,id' --jq '.[] | select(.name != "Deploy Worker") | .id' | xargs -I! gh workflow disable !
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: worker
